### ISSUE TITLE
backport

### ISSUE THREAD

**Issue by frost91001-flare** [FrostbyteGames1/Frostbytes-Improved-Inventory#11]
i was wondering i there will ever be a back port for 1.20.4 for the new features like the additional quick cycle preview?

**Comment by FrostbyteGames1** [comment]
It isn't planned, but I can look into it once I've finished updating Slabs and Stairs to 1.21.

**Comment by FrostbyteGames1** [comment]
As of v1.6.2, the new features have been backported to 1.20.4
