### ISSUE TITLE
Add config for cursor locking changes

### ISSUE THREAD

**Issue by andersmmg** [FrostbyteGames1/Frostbytes-Improved-Inventory#13]
I want to be able to use container tabs, but having them enabled changes the cursor lock behavior in an annoying way. I'd like to be able to disable that but keep container tabs rather than the cursor locking just using the container tabs setting

**Comment by FrostbyteGames1** [comment]
As of v1.9.2, the cursor movement should be much less annoying, but I have also added a config option to revert it to vanilla.

**Comment by andersmmg** [comment]
I tested it and it seems to work much better, thanks!
