### ISSUE TITLE
Game crash on config

### ISSUE THREAD

**Issue by AvailableUsername3** [FrostbyteGames1/Frostbytes-Improved-Inventory#14]
Everytime that I try to configurate the mod using mod menu, the game says saving world (even if you aren't in a world or server) crashes and spews the message: 

The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: 'void net.frostbyte.inventory.config.ImprovedInventoryConfigScreen.method_25420(net.minecraft.class_332, int, int, float)'

Is there any way to fix this?

**Comment by FrostbyteGames1** [comment]
Which version of the mod are you using, and can you share the config file?

**Comment by AvailableUsername3** [comment]
I'm using the 1.22 version of the mod, because its the only version i can use with my 1.20.1 modpack, and here is the config:
[improved-inventory.json](https://github.com/user-attachments/files/15963885/improved-inventory.json)

**Comment by FrostbyteGames1** [comment]
This should now be fixed as of v.1.2.3.
