### ISSUE TITLE
Any known compatibility issues?

### ISSUE THREAD

**Issue by SpringApricot** [FrostbyteGames1/Frostbytes-Improved-Inventory#19]
I just installed the mod and a tones of feature's not working. No paper doll, no colored armor, no stack refill, no container tabs... Out of the features I tested, slot cycling, tool select, durability display and zoom work, and half of those aren't even ones I wanted when downloading the mod x)
I have tones of mods installed, so I kinda expect this to be a compatibility issue - are there any mods known to be incompatible with this one?
(I'm on fabric, 1.20.4)

**Comment by FrostbyteGames1** [comment]
Many of these features were introduced in later versions, but I have now backported them to 1.20.4 (as of v1.6.2).
