### ISSUE TITLE
1.20.4 Stack Refil leaves a single item in my inventory and doesn't take the whole stack

### ISSUE THREAD

**Issue by jhughes-dev** [FrostbyteGames1/Frostbytes-Improved-Inventory#2]
When the items are pulled from inventory, instead of a new full stack, I get one less on the task bar and a single item is left in the inventory.

**Comment by FrostbyteGames1** [comment]
I haven't been able to recreate this. Are you able to provide a video of the issue?

**Comment by jhughes-dev** [comment]
Just about to go on vacation for two weeks. Could be an interaction with another mod. If I see it when I get back, I'll see what I can do.

**Comment by FrostbyteGames1** [comment]
> I haven't been able to recreate this. Are you able to provide a video or screenshots of the issue?

Nevermind, I figured out what you were talking about. It should be fixed now (as of v1.5.0).

**Comment by jhughes-dev** [comment]
Thanks, I'll check this out when I get home.
