### ISSUE TITLE
Crash in 1.20,1

### ISSUE THREAD

**Issue by mrunkn0wn** [FrostbyteGames1/Frostbytes-Improved-Inventory#21]
whenever I tried to open the configure menu , game says , saving world and crashes 
am using all dependency and other requirements idk the reason why

**Comment by mrunkn0wn** [comment]
any fix?

**Comment by FrostbyteGames1** [comment]
This was fixed in later versions of Minecraft, but if you want to use the mod in 1.20.1, you will have to wait for me to backport

**Comment by mrunkn0wn** [comment]
ahh take ur time np man

**Comment by FrostbyteGames1** [comment]
This should now be resolved as of v1.2.4

**Comment by FrostbyteGames1** [comment]
Your PC may be running Java 21, but Minecraft seems to be using Java 17. Either way, I will try changing the mod's java version.

**Comment by FrostbyteGames1** [comment]
The newest 1.20.1 version should resolve this crash
