### ISSUE TITLE
FOV change when loading into game. Fabric 1.21

### ISSUE THREAD

**Issue by hieuhho** [FrostbyteGames1/Frostbytes-Improved-Inventory#22]
The POV value is changed to 90 when first loading into a single player world / multiplayer server. Unsure if this is due to incompatibility with other mods but issue goes away if I disable the mod.

Steps to replicate: 
1. Set POV to Normal
2. Quit Minecraft completely
3. Start Minecraft (POV is still Normal at this point)
4. Load into a single/multi player world
5. POV is now set as 90

I even set options.txt to Read Only and this still happens. 

Attached my settings below
[improved-inventory.json](https://github.com/user-attachments/files/16230288/improved-inventory.json)

**Comment by FrostbyteGames1** [comment]
This should now be fixed as of v1.9.6
