### ISSUE TITLE
1.20.4 fabric version requires java 1.21

### ISSUE THREAD

**Issue by SpringApricot** [FrostbyteGames1/Frostbytes-Improved-Inventory#23]
1.20.4 by default uses java 1.17, meanwhile the current 1.20.4 fabric mod version requires java 1.21. as far as I googled it's not recommended to hop onto 1.21 java due to stability etc. Would it be possible to make it compatible with java 1.17?
![image](https://github.com/user-attachments/assets/34e08fb1-4046-4c80-b531-424d03053718)

**Comment by CocoManiaDX** [comment]
Just adding that this is also the case for the 1.20.1 version (1.2.4)

**Comment by FrostbyteGames1** [comment]
v1.6.4 for 1.20.4 now uses Java 17.
