### ISSUE TITLE
Serious bug

### ISSUE THREAD

**Issue by SnowCutieOwO** [FrostbyteGames1/Frostbytes-Improved-Inventory#24]
The inventory sorting option always activating, which means if you set hot key to middle-mouse-click, the vanilla block select function will be disabled.

**Comment by FrostbyteGames1** [comment]
As far as I can tell, this is a vanilla bug when multiple behaviors have the same keybind. I am looking into a way to get around this without having to use another mod.

**Comment by SnowCutieOwO** [comment]
> As far as I can tell, this is a vanilla bug when multiple behaviors have the same keybind. I am looking into a way to get around this without having to use another mod.

Excellent, I'll wait for you <3

**Comment by FrostbyteGames1** [comment]
As of v1.9.7, this should be resolved. I am still working on backporting this fix to the 1.20.x versions
