### ISSUE TITLE
The stack refill not working

### ISSUE THREAD

**Issue by cooljoey6864y** [FrostbyteGames1/Frostbytes-Improved-Inventory#26]
The stack refill is not refilling the stack

https://github.com/user-attachments/assets/237f30d8-b5d7-4479-8e2b-6f48dc15d282

**Comment by FrostbyteGames1** [comment]
With which version of the mod are you experiencing this issue?
Also, just to clarify, stack refill pulls matching stacks from the inventory, not from the hotbar.

**Comment by cooljoey6864y** [comment]
1.9.6
