### ISSUE TITLE
Black/blank screen issue

### ISSUE THREAD

**Issue by p0nx77** [FrostbyteGames1/Frostbytes-Improved-Inventory#27]
Hi, so yeah im getting a black screen whenever I join my world using this mod. I already turned off shaders, but still the same issue. I also turned off some options from the mod, but no luck. I just get a white/blank/black screen on every world I try to join. Please help?

MC 1.21, Fabric 0.16.0, mod ver: 1.9.6 (Fabric 1.21)

No errors, no crash logs.

plz help, I really want to try this mod

![2024-07-30_13 56 05](https://github.com/user-attachments/assets/5722fe39-56b8-48bc-a135-821731c0ad44)

**Comment by FrostbyteGames1** [comment]
What does the game say that the FOV is set to?

**Comment by p0nx77** [comment]
Hi, So i Just fixed this. I went into options, and noticed that the FOV was set to negative. literally the "drag" icon was out of the FOV box, like -50 or something. I grabbed it, and took it back to 80, reloaded my shaders, and boom, I can see everything normal now. I did not touch my FOV before installing this mod. any ideas on what could happened?

**Comment by FrostbyteGames1** [comment]
Most likely I broke something while messing with the zoom code, but now that I know what is causing this I will have a better idea of how to go about fixing it.

**Comment by p0nx77** [comment]
No worries, thanks for the fast response! The mod is working great, I really like it. One thing I just noticed, the "pick block" (middle button) its conflicting with the sorting option, and for some reason is not allowing to perform both actions even thou it has the same button. Meaning that, I can sort my inventory with middle button, but I cant pick blocks when using the middle mouse button.

**Comment by FrostbyteGames1** [comment]
Unfortunately that's a vanilla bug that sometimes happens when a key has multiple actions bound to it. I'm looking into a way to fix it, but in the meantime I recommend using a mod like [Too Many Shortcuts](https://modrinth.com/mod/too-many-shortcuts)

**Comment by p0nx77** [comment]
got it. thansk Frostbyte!

**Comment by FrostbyteGames1** [comment]
As of v1.9.7, keybinds no longer conflict if they are bound to the same key
