### ISSUE TITLE
Config - Automatic Tool Selection

### ISSUE THREAD

**Issue by lanwoodall423** [FrostbyteGames1/Frostbytes-Improved-Inventory#28]
I think the option to prevent automatic switching while holding a weapon would be good. 

1. If I have two melee weapons ex. a dagger and a spear, hitting a hostile mob with the dagger causes swapping the spear because it does more damage.
2. If I accidentally hit the ground while fighting I will be autoswapped to a tool.

**Comment by FrostbyteGames1** [comment]
A blacklist has been added for both stack refill & tool select as of v1.9.8. Stack refill won't refill any items that are in its blacklist, and tool select won't swap away from any items that are in its blacklist.

**Comment by lanwoodall423** [comment]
could it be backported to 1.20.1?

**Comment by FrostbyteGames1** [comment]
I am in the process of backporting to 1.20.1, 1.20.4, and 1.20.6, but it will take some time

**Comment by FrostbyteGames1** [comment]
The blacklist feature has been backported to 1.20.1 as v1.2.6
