### ISSUE TITLE
Game spams console with error message every tick an inventory is opened

### ISSUE THREAD

**Issue by Lassoloc** [FrostbyteGames1/Frostbytes-Improved-Inventory#29]
These error messages are spammed into the console many times a second whenever I have an inventory (player inventory, chest, etc.) open.

Game version: 1.21 Fabric
Mod version: 1.9.6

Config settings: [link](https://github.com/user-attachments/files/16521498/improved-inventory.json)

Console screenshot:
![screenshot](https://github.com/user-attachments/assets/1f6090f9-74f2-4236-a200-a98ddeccfc08)

Mod list:
![screenshot](https://github.com/user-attachments/assets/3cc3faae-88ab-4d13-baf8-89538507eba6)

**Comment by FrostbyteGames1** [comment]
Is this still an issue on v1.9.8?

**Comment by Lassoloc** [comment]
busy with family stuff and don't have time to check at the moment but i can let you know in the next few days

**Comment by Lassoloc** [comment]
confirming issue is fixed
