### ISSUE TITLE
Tool Swap swaps to wrong tool

### ISSUE THREAD

**Issue by WimpieRatte** [FrostbyteGames1/Frostbytes-Improved-Inventory#3]
When harvesting glow lichen, it swaps to my axe, instead of the shears.
Also, when breaking grass, it seems to swop to my shovel. Ideally, something like grass shouldn't need any swapping because it breaks instantly.

This was with mod version 1.5.0 in Fabric version 1.20.4.

**Comment by FrostbyteGames1** [comment]
As of v1.6.0, I have added shears to the list of tools that can be swapped to. I also added a 2 tick delay between when the block starts to be broken and when the tool is swapped, which should stop the tool from swapping for blocks that beak instantly by hand.

**Comment by WimpieRatte** [comment]
wow, that was quick!
thank you very much!
