### ISSUE TITLE
I can't join worlds using this mod.

### ISSUE THREAD

**Issue by James-Fire** [FrostbyteGames1/Frostbytes-Improved-Inventory#30]
The game freezes on Loading Terrain in both single and multiplayer, even on a new singleplayer world. Servers do acknowledge that I have joined the server. Disabling this mod stops this issue.

I am using this modlist

![image](https://github.com/user-attachments/assets/c43c920d-0e55-4f67-85c6-324b856c62d0)
![image](https://github.com/user-attachments/assets/555e9bb2-b3c4-47e3-95f2-e2f72f9b9e55)

This is the logfile

[latest.log](https://github.com/user-attachments/files/16629654/latest.log)

Do some of the features conflict somehow? I was going to do the config in-game, so whatever the defaults are are what is set currently.

**Comment by FrostbyteGames1** [comment]
I'm not entirely sure why that is happening, as the log doesn't indicate that anything is wrong. I've also tried launching Minecraft with the same mod list, and everything seems to be working fine, which means I don't have a good way of troubleshooting.

Based on the screenshots, I assume that you are using the CurseForge launcher. If so, does the issue persist when using the vanilla launcher or a different third party launcher? I don't really expect this to be the issue, but it couldn't hurt to test.

**Comment by James-Fire** [comment]
Okay someone else I gave this modlist to had it work fine, and I was able to get it to work after deleting and re-downloading the mod.

I have no idea what was wrong, but it's no longer an issue
