### ISSUE TITLE
Crash from seemingly your mod (I swear this is a real issue this time :D)

### ISSUE THREAD

**Issue by James-Fire** [FrostbyteGames1/Frostbytes-Improved-Inventory#31]
[crash-2024-08-15_23.58.00-client.txt](https://github.com/user-attachments/files/16633510/crash-2024-08-15_23.58.00-client.txt)

**Comment by FrostbyteGames1** [comment]
While I work on a fix, you should be able to avoid the crash by setting the "containerTab" config option to false.
