### ISSUE TITLE
1.9.4+ backport for 1.20.1

### ISSUE THREAD

**Issue by Yechse** [FrostbyteGames1/Frostbytes-Improved-Inventory#32]
I wanna add your mod into my 1.20.1 modpack with raised mod but 1.2.5 version of your mod doesnt meet my requirements and it crashes whenever i try to open the config menu. To make it compatible with raised mod i need to change the places of hud elements. It looks like you added x, y properties for hud elements and thats what i want.

It would be pretty cool if you backport 1.9.4 or newer versions of your mod to 1.20.1.

**Comment by FrostbyteGames1** [comment]
v1.9.9 has been backported to 1.20.1 as v1.2.6
