### ISSUE TITLE
Tool auto-swap just always switches away from the mace

### ISSUE THREAD

**Issue by James-Fire** [FrostbyteGames1/Frostbytes-Improved-Inventory#33]
So I tried to do some killing of iron golems with a mace. At first, it would swap to my sword every time I hit, so I put my sword in my inventory instead of my hotbar. Then it would always switch to my empty slot one, which my sword was above, so I put the mace there. Then it always switched to the baked potatoes in my slot 2.

Not sure why it's switching at all, but it makes it pretty unusable.

**Comment by James-Fire** [comment]
1.9.9 seems to not exist?

I do see a 1.9.10, which the curseforge launcher has decided is a lower version than 1.9.8 :D

**Comment by FrostbyteGames1** [comment]
That's the right version, I messed up when naming the file, and now CF sees 1.9.10 as 1.9.1, which it thinks cones before 1.9.8.

**Comment by James-Fire** [comment]
Beautiful

Truly an amazing piece of technology we have here

**Comment by James-Fire** [comment]
On 1.9.10, this is still happening.

Exact same issue, it swaps to anything other than the mace, preferring tools first

**Comment by FrostbyteGames1** [comment]
v1.9.11 should resolve the issue (for real this time).

**Comment by James-Fire** [comment]
It did not.

**Comment by James-Fire** [comment]
Also just in general it seems that if the auto-swap doesn't know what it should use for something, it just defaults to sword?

Can you make the default instead be to not switch?

Also, what does the "toolSelectBlacklist": "[]", in the config do?

**Comment by FrostbyteGames1** [comment]
> Also just in general it seems that if the auto-swap doesn't know what it should use for something, it just defaults to sword?

Good to know, I'll look into it.

> Also, what does the "toolSelectBlacklist": "[]", in the config do?

It stops the mod from swapping if the current held item is in the blacklist. For example, "toolSelectBlacklist": "[minecraft:mace, minecraft:stone_axe]" should stop the mod from swapping away from a mace or a stone axe, even if a "better" tool is found.

**Comment by FrostbyteGames1** [comment]
Are you able to provide a short recording of the issues? I haven't been able to recreate them in my testing.

**Comment by James-Fire** [comment]
Just in case it's relevant, this is my config

{
  "duraDisplay": false,
  "duraDisplaySide": "LEFT",
  "duraDisplayOffsetX": 0,
  "duraDisplayOffsetY": 0,
  "slotCycle": true,
  "slotCycleOffsetX": 41,
  "slotCycleOffsetY": 0,
  "stackRefill": true,
  "stackRefillPreview": true,
  "stackRefillPreviewColor": -1,
  "stackRefillBlacklist": "[]",
  "toolSelect": true,
  "toolSelectBlacklist": "[]",
  "paperdoll": false,
  "paperdollSide": "LEFT",
  "paperdollOffsetX": 0,
  "paperdollOffsetY": 0,
  "zoomFOV": 30,
  "zoomScrollRequiresControl": true,
  "zoomSound": true,
  "gamma": 500,
  "maxInteractions": 0,
  "containerSearch": true,
  "containerTab": false,
  "containerTabFreeCursor": true,
  "shulkerBoxTooltip": true,
  "mapTooltip": true,
  "heldItemsVisibleInBoat": true,
  "armorBarColors": true
}

Here's vid of mace

https://cdn.discordapp.com/attachments/888589621078929458/1320934790157041775/javaw_GjN9tLD5C3.mp4?ex=676b67e3&is=676a1663&hm=5c4476ecbf128bec30a0246b58f3c9b9fa6201dd6c92cc8e562438d6b93c3fbb&

**Comment by James-Fire** [comment]
![image](https://github.com/user-attachments/assets/ba331762-e19e-4e39-9c14-958afd1282d9)
And I am on 1.9.11 on 1.21.4

**Comment by James-Fire** [comment]
I can confirm the other cases I've mentioned in the other issue are fixed though. Those being Vines, Dripleaf, and Item Frames

**Comment by FrostbyteGames1** [comment]
Thanks for the additional info. While I work on a fix, see if adding the mace to the tool select blacklist stops it from switching.

**Comment by FrostbyteGames1** [comment]
Also, when you say that the tool selector defaults to swords, in what case(s) does it do that? (ie. is it for specific entities and/or blocks?)

**Comment by James-Fire** [comment]
Previously, it was doing that for Item Frames, Dripleaf, and Vines. Which, respectively, have no tool, no tool, and shears. And you fixed those ones at least. Idk if you've already made such a change, but I have not so far found any other cases to report.

Adding the mace to the blacklist does appear to work.

**Comment by FrostbyteGames1** [comment]
As of v1.9.12, the mace should be treated as always being in the blacklist, even if not specified in the config. This will hopefully resolve the issue.

**Comment by James-Fire** [comment]
:D
