### ISSUE TITLE
When breaking or removing items from item frames, it switches to a sword

### ISSUE THREAD

**Issue by James-Fire** [FrostbyteGames1/Frostbytes-Improved-Inventory#34]
It takes one hit regardless of what you have equipped, so there's no point to switching the tool.

**Comment by James-Fire** [comment]
It also happened to me now with Vines when I didn't have shears, and it also happened for dripleaf

**Comment by James-Fire** [comment]
Also for tree leaves

**Comment by FrostbyteGames1** [comment]
Sorry for the wait, this should now be resolved as of v.1.9.10.
