### ISSUE TITLE
Infinite sorting

### ISSUE THREAD

**Issue by justendmeplease** [FrostbyteGames1/Frostbytes-Improved-Inventory#4]
Whenever I open any inventory it is sorted infinitely which is not only kinda annoying but also ends up crashing my game if I open a chest.

**Comment by FrostbyteGames1** [comment]
What version of the mod are you using, and what is your sort key?

**Comment by Patrykowski8** [comment]
I have the same problem. I have version 1.20.6, sorting does not work (I use the middle mouse button). I also get kicked from the game after opening the chest

**Comment by FrostbyteGames1** [comment]
I have found the source of the crash, and it should be resolved as of v1.7.2.

**Comment by FrostbyteGames1** [comment]
What container(s) does sorting not work for? And is it specific to one gamemode?

**Comment by Laser123454321** [comment]
I have the same issue, running 1.7.3 on MC 1.20.6 survival multiplayer opening and sorting a standard double chest. Still causes game crash.

**Comment by FrostbyteGames1** [comment]
@Laser123454321 Can you provide the log/crash report?

**Comment by Laser123454321** [comment]
Not a crash exactly, so no crash log, main minecraft log just reports
"[Render thread/WARN]: Client disconnected with reason: Timed out"

I took video, here is a link
https://youtu.be/kM1Gt42B-z8

**Comment by FrostbyteGames1** [comment]
I've just uploaded v1.7.4 to Modrinth and Curseforge, which should (hopefully) resolve the desync issue.

**Comment by FrostbyteGames1** [comment]
The issue is confirmed as resolved as of v1.7.7. This version includes a config option to limit the number of interactions created each game tick. The timeout issue is resolved by setting this config option to ~30.
