### ISSUE TITLE
Continuous clicking when in inventory or container

### ISSUE THREAD

**Issue by AethanFoot** [FrostbyteGames1/Frostbytes-Improved-Inventory#5]
This happens on 1.7.1 and 1.7.2. It sounds like a gui button is being rapidly clicked, could be related to #4. Im unsure if this is some strange interaction with another mod, which i could test if useful. (Also as a side note no sorting seems to ever happen). 

Many thanks!

**Comment by FrostbyteGames1** [comment]
What container(s) does sorting not work for? And is it specific to one gamemode?

**Comment by AethanFoot** [comment]
Okay, sorting does seem to work mostly actually, but when on a realm is causes a desync with the server (when i sort a chest i can no longer interact with anything, and when i rejoin the sort was not passed to the server).

Many Thanks!

**Comment by FrostbyteGames1** [comment]
Good to know, I will look into the cause of the desync.

**Comment by FrostbyteGames1** [comment]
After further investigation, it seems that the desync issue is unique to realms, as it doesn't appear to happen in singleplayer or on a server. As a result, I am unsure how to resolve it at this time.

However, the sound spam issue should now be resolved as of v1.7.3.

**Comment by AethanFoot** [comment]
Can confirm the clicking is fixed. Annoyingly there is no error provided other than timed out for the desync issue. Other mods I used in 1.20.4 didnt cause any issues on realms so I dont think it would be the server blocking it, but it could a different implementation that the server doesnt like. (As a note i used inventory profiles next, if i find time i will look through to see what difference there could be)

**Comment by FrostbyteGames1** [comment]
I've just uploaded v1.7.4 to Modrinth and Curseforge, which should (hopefully) resolve the desync issue.

**Comment by AethanFoot** [comment]
Ill have time to take a look tomorrow

**Comment by AethanFoot** [comment]
Unfortunately it doesnt appear to be fixed,  maybe 1.20.6 changed realms to block this. 

I will continue to test through the week.

**Comment by AethanFoot** [comment]
I have found that it seems to timeout when there are more than 13 different stackable items (annoyingly this doesnt seem repeatable between containers and items). So idk if the realms is blocking after a certain number, but seems it would be a strange change for them to make.

**Comment by FrostbyteGames1** [comment]
In that case, the cause may be that realms doesn't like receiving too many player inputs in a short time. I wonder if using an auto clicker would result in a timeout as well?

**Comment by AethanFoot** [comment]
I tried an auto clicker, but it only input actions every 2 ticks which was more than fine. I can try and setup for being able to build and test at some point, but looking over I was thinking that it may be beneficial to collect the items into an array list (or a map if you need to track their index  in the container) and sort them in the code to reduce the call into the game. If this seems to much or you know a better thing in the libraries, let me know and I can setup to do it and will make a PR with the changes.

Many thanks!

**Comment by FrostbyteGames1** [comment]
I've pushed an update that sorts an ArrayList of ItemStacks and then updates the container accordingly, which should mean that interactions are only created when absolutely necessary for the sorting to work.

If this still causes the timeout, I can also try experimenting with putting a hard cap on the number of interactions created per game tick.

**Comment by AethanFoot** [comment]
It seems unhappy with the compare method being used within the sort. It appears to have some transitivity issues with the error:
```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
	at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
	at java.base/java.util.TimSort.sort(TimSort.java:245)
	at java.base/java.util.Arrays.sort(Arrays.java:1308)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1804)
	at net.frostbyte.inventory.InventorySorter.getSortedStackArray(InventorySorter.java:129)
	at net.frostbyte.inventory.InventorySorter.sortStacks(InventorySorter.java:137)
	at net.frostbyte.inventory.InventorySorter.onEndTick(InventorySorter.java:64)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$bim000$fabric-lifecycle-events-v1$onEndTick(class_310.java:11247)
	at net.minecraft.class_310.method_1574(class_310.java:2063)
	at net.minecraft.class_310.method_1523(class_310.java:1281)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

My best guess by just looking is at it is there is no equivalence tests returning 0. 

Many Thanks!

**Comment by FrostbyteGames1** [comment]
An updated version has been pushed, the comparator should work properly now

**Comment by AethanFoot** [comment]
Yes that works, unfortunately still causes it to timeout. If you restrict the interactions, would it be worth it to add an option to toggle this to prevent slower sorts when not necessary,

Many Thanks!

**Comment by AryuSyrius** [comment]
Hello. I am getting the clicking noise in my inventory as well, and the sorting is not working at all in any container that I tried. I was using 1.7.1 from Modrinth on MC version 1.20.5. I host my own dedicated server. Unfortunately it does not look like I can try any mod version above 1.7.1 on MC version 1.20.5. Let me know what info you need from me.

**Comment by FrostbyteGames1** [comment]
v1.7.7 has been released, and includes a config option to limit the number of interactions per game tick (set to 0 to disable the limit.)

This version is compatible with both 1.20.5 and 1.20.6.

**Comment by AryuSyrius** [comment]
> v1.7.7 has been released, and includes a config option to limit the number of interactions per game tick (set to 0 to disable the limit.)
> 
> This version is compatible with both 1.20.5 and 1.20.6.

Okay, I might not know how to tell Modrinth to let me use that version. Regardless, I went ahead and upgraded my server to 20.6 so I've got your mod installed and working. Just to clarify, it is supposed to sort the player's inventory?

**Comment by FrostbyteGames1** [comment]
> Okay, I might not know how to tell Modrinth to let me use that version.

You don't have to, the same jar file is automatically compatible with every version that is listed as supported.

> Just to clarify, it is supposed to sort the player's inventory?

No, it sorts the container that the player currently has open, such as chests, hoppers, shulkers, etc.

**Comment by AethanFoot** [comment]
Amazing it seems to work now! It initial testings 30 per tick seems to work on realms were 40 times out (for anyone looking). 

 Many Thanks!
