### ISSUE TITLE
1.8.2 - Game wont Launch, tried multiple versions

### ISSUE THREAD

**Issue by 4HMZ4** [FrostbyteGames1/Frostbytes-Improved-Inventory#7]
Not sure which information is helpful here but. Here are system specs as well as logs from GDLauncher.
 
 Running GDLauncher.
 Linux - PoP-OS
 Java 21
 Inventory-1.8.2.jar
 
 I should mention I also tried on a windows machine using MultiMC

This seems to be the only inventory sorting mod on 1.20.6 at the moment, not sure if this is just a me issue but borked across 2 devices.
 
```
 GDLauncher@N/A: ---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2024-05-29 21:22:07
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'inventory'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.
```

**Comment by 4HMZ4** [comment]
Downgrading to 1.7.7 seemed to work, however it looks like it is lacking the inventory sort feature

**Comment by FrostbyteGames1** [comment]
It seems I made a mistake when defining the dependency for [YetAnotherConfigLib](https://modrinth.com/mod/yacl/version/3.4.4+1.20.6-fabric). v1.8.x requires the user to download yacl, but I forgot to add it to the mod's requirements. This should be fixed as of v1.8.3, but v1.8.2 should also work when yacl is installed.

**Comment by 4HMZ4** [comment]
@FrostbyteGames1 Could you update the README to prevent launching the game to then find out you need the dependency.

**Comment by FrostbyteGames1** [comment]
README has been updated in all places
