### ISSUE TITLE
Additional quick cycle preview

### ISSUE THREAD

**Issue by lehmanju** [FrostbyteGames1/Frostbytes-Improved-Inventory#8]
First, thanks for creating this useful mod. There's a feature I'd like to see for quick cycling items. Currently, the preview on the right of the inventory bar shows the current item and the two adjacent/next items. Would it be possible to show all possible other items? Either displaying four item boxes with all items of a column or replacing the currently selected item with the remaining selectable item. The current item is already visible in the usual inventory bar.

This would allow quick cycling without opening the inventory to see which slot has the required item or doing an unnecessary cycle/cycle back step.

**Comment by FrostbyteGames1** [comment]
Thanks for the suggestion. As of v1.9.0, the preview now shows the three items in the same column rather than the two selectable items and the current item.
